// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Testes Suite LP4', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('abaixoDoPesoHomem', async function() {
    await driver.get("http://127.0.0.1:3000/index.html")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("20.6")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("h")
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.css("html")).click()
    assert(await driver.findElement(By.id("result")).getText() == "abaixo do peso : 20.6")
  })
  it('abaixoDoPesoMulher', async function() {
    await driver.get("http://127.0.0.1:3000/")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("19")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("m")
    await driver.findElement(By.id("btn")).click()
    {
      const element = await driver.findElement(By.id("btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("result")).click()
    assert(await driver.findElement(By.id("result")).getText() == "abaixo do peso : 19")
  })
  it('acimaDoPesoIdealHomem', async function() {
    await driver.get("http://127.0.0.1:3000/")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("31")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("h")
    await driver.findElement(By.id("btn")).click()
    {
      const element = await driver.findElement(By.id("btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("result")).click()
    assert(await driver.findElement(By.id("result")).getText() == "acima do peso ideal : 31")
  })
  it('marginalmenteAcimaDoPesoHomem', async function() {
    await driver.get("http://127.0.0.1:3000/")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("27.7")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("h")
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.id("result")).click()
    assert(await driver.findElement(By.id("result")).getText() == "marginalmente acima do peso : 27.7")
  })
  it('marginalmenteAcimaDoPesoMulher', async function() {
    await driver.get("http://127.0.0.1:3000/")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("27.2")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("m")
    await driver.findElement(By.id("btn")).click()
    {
      const element = await driver.findElement(By.id("btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("result")).click()
    assert(await driver.findElement(By.id("result")).getText() == "marginalmente acima do peso : 27.2")
  })
  it('noPesoNormalHomem', async function() {
    await driver.get("http://127.0.0.1:3000/")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("26.3")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("h")
    await driver.findElement(By.id("btn")).click()
    {
      const element = await driver.findElement(By.id("btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("result")).click()
    assert(await driver.findElement(By.id("result")).getText() == "no peso normal : 26.3")
  })
  it('noPesoNormalMulher', async function() {
    await driver.get("http://127.0.0.1:3000/")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("25.7")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("m")
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.id("result")).click()
    assert(await driver.findElement(By.id("result")).getText() == "no peso normal : 25.7")
  })
  it('obesoHomem', async function() {
    await driver.get("http://127.0.0.1:3000/")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("31.1")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("h")
    await driver.findElement(By.id("btn")).click()
    {
      const element = await driver.findElement(By.id("btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("result")).click()
    assert(await driver.findElement(By.id("result")).getText() == "Obeso : 31.1")
  })
  it('obesoMulher', async function() {
    await driver.get("http://127.0.0.1:3000/")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("32.3")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("m")
    await driver.findElement(By.id("btn")).click()
    {
      const element = await driver.findElement(By.id("btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("result")).click()
    assert(await driver.findElement(By.id("result")).getText() == "Obeso : 32.3")
  })
  it('sexoInvalido', async function() {
    await driver.get("http://127.0.0.1:3000/")
    await driver.manage().window().setRect({ width: 697, height: 728 })
    await driver.findElement(By.id("altura")).click()
    await driver.findElement(By.id("altura")).sendKeys("1")
    await driver.findElement(By.id("peso")).click()
    await driver.findElement(By.id("peso")).sendKeys("1")
    await driver.findElement(By.id("sexo")).click()
    await driver.findElement(By.id("sexo")).sendKeys("g")
    await driver.findElement(By.id("btn")).click()
    await driver.findElement(By.id("result")).click()
    assert(await driver.findElement(By.id("result")).getText() == "Sexo não válido")
  })
})
