// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestesSuiteLP4Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void abaixoDoPesoHomem() {
    driver.get("http://127.0.0.1:3000/index.html");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("20.6");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("h");
    driver.findElement(By.id("btn")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("abaixo do peso : 20.6"));
  }
  @Test
  public void abaixoDoPesoMulher() {
    driver.get("http://127.0.0.1:3000/");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("19");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("m");
    driver.findElement(By.id("btn")).click();
    {
      WebElement element = driver.findElement(By.id("btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("result")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("abaixo do peso : 19"));
  }
  @Test
  public void acimaDoPesoIdealHomem() {
    driver.get("http://127.0.0.1:3000/");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("31");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("h");
    driver.findElement(By.id("btn")).click();
    {
      WebElement element = driver.findElement(By.id("btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("result")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("acima do peso ideal : 31"));
  }
  @Test
  public void marginalmenteAcimaDoPesoHomem() {
    driver.get("http://127.0.0.1:3000/");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("27.7");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("h");
    driver.findElement(By.id("btn")).click();
    driver.findElement(By.id("result")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("marginalmente acima do peso : 27.7"));
  }
  @Test
  public void marginalmenteAcimaDoPesoMulher() {
    driver.get("http://127.0.0.1:3000/");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("27.2");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("m");
    driver.findElement(By.id("btn")).click();
    {
      WebElement element = driver.findElement(By.id("btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("result")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("marginalmente acima do peso : 27.2"));
  }
  @Test
  public void noPesoNormalHomem() {
    driver.get("http://127.0.0.1:3000/");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("26.3");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("h");
    driver.findElement(By.id("btn")).click();
    {
      WebElement element = driver.findElement(By.id("btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("result")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("no peso normal : 26.3"));
  }
  @Test
  public void noPesoNormalMulher() {
    driver.get("http://127.0.0.1:3000/");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("25.7");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("m");
    driver.findElement(By.id("btn")).click();
    driver.findElement(By.id("result")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("no peso normal : 25.7"));
  }
  @Test
  public void obesoHomem() {
    driver.get("http://127.0.0.1:3000/");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("31.1");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("h");
    driver.findElement(By.id("btn")).click();
    {
      WebElement element = driver.findElement(By.id("btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("result")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("Obeso : 31.1"));
  }
  @Test
  public void obesoMulher() {
    driver.get("http://127.0.0.1:3000/");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("32.3");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("m");
    driver.findElement(By.id("btn")).click();
    {
      WebElement element = driver.findElement(By.id("btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("result")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("Obeso : 32.3"));
  }
  @Test
  public void sexoInvalido() {
    driver.get("http://127.0.0.1:3000/");
    driver.manage().window().setSize(new Dimension(697, 728));
    driver.findElement(By.id("altura")).click();
    driver.findElement(By.id("altura")).sendKeys("1");
    driver.findElement(By.id("peso")).click();
    driver.findElement(By.id("peso")).sendKeys("1");
    driver.findElement(By.id("sexo")).click();
    driver.findElement(By.id("sexo")).sendKeys("g");
    driver.findElement(By.id("btn")).click();
    driver.findElement(By.id("result")).click();
    assertThat(driver.findElement(By.id("result")).getText(), is("Sexo não válido"));
  }
}
